language: go

go:
  - 1.7.x

env:
  global:
    - UNAME="$(uname | tr '[:upper:]' '[:lower:]')"
    - secure: MNojXFxIklmrjWoe49y8r+WlCRTZ8mm1XyNU5J4RLBwFXCdc8kCqOV97pc+JoPLVh7wfKISCXjT7apMIO8lg3Clcc0QXKZgewL1JBMvezxt3DNlgrnQNbh94cQVVM6g8n86UK/aRq2LNg3rCq1qjv1weqTBYGto1YElDmndjmYSVSRGne31jkaIEZuhIp+A505rUzzNESUbCV6b0TZLK3XgbYBDOYtIqxhMNt3VTQKaNNRnjhSNS7fqIHrXVxp96vhKxqgFr34Oqm0Xps583jgqU2H21hx4GYtEXit+YOxqG7szwHiIz8PLDz3FOQStxtqSFut0IR1yiVCbkGAgozbnpN4Jysq0s0+n6g7oFx+6CyqTMFibmCXzTFd6Vw+xBNMEkv5isS4AdUB7ccDPaXb53m4dnEZ2vFFGe//l2DzXdIlfQLbGW5EdWmjbaSCQuLfmb8Oy1S4nffn+l84KcSn5iPoMpESWf1QDysxCulY9u/Pi8a2DqwQFZZT/lsycdPQE2vS6/IgqRL94/v3/cAaMGM6OAwFjR/esGQAzJNJZ9IqYyugVhNnWyI83HZYrptwqC7crNHwbvRKE3yxng0gi8nYKCI/8p6ZbIR+RXBp+aHuUniTnqKlwcZEXy0GFiR4jVEIzxpnuT147t5kfuoHMulsrx45AxRQ+Ehai+TZw=

  matrix:
    - NODE_VERSION="4.2.0"

cache:
  directories:
    - node_modules

before_install:
  - rm -rf ~/.nvm/ && git clone --depth 1 https://github.com/creationix/nvm.git ~/.nvm
  - source ~/.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - npm install -g bower
  - npm install -g gulp
  - go get github.com/FiloSottile/gvt
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - go env && pwd

after_success:
  - sh ./bin/set_tags.sh

script:
  - ./bin/make.sh --init
  - ./bin/make.sh --build-front
  - $HOME/gopath/bin/goveralls -service=travis-ci -repotoken $COVERALLS_TOKEN
  - ./bin/make.sh --build-back

deploy:
  provider: releases
  api_key:
    secure: ATrNFZsdoLkKAErnXHoFzn7caVZ71h/m9mKGKH8AUWBg82jYIPhq/zC7WibA6LOieNBb9anczP+TphlSKLN+r1clACVStez0sExMEArTtmh8WOFAuFpwmjoILofJvYbbhUXy/YLwXjAab7ovfc8Og0HEKvKRqrDBjC0qRx8RLIPzU+Sx4/RBbEi1RuPT9yymjOONe/m943M0SS9owO8lath6XBoopJI1DCE6rFjMGg5/m6ie9xY25Rpcdb3DKB1rerEACe9B1/90jRkjlQFuE7L/BLc8ZsJGlH3c+q3B3NK8xlR9a8fw+mpz1TDXJLdulYlb0Hc+xYmX8lJEhALd4EMgi+23nsf5OVvqslLtW+Vsrs6w2dF+5tuSNuljZi0P+qEw9vQHWzvIsKxp/PKW9uTGp+Py/KcA/2fPxwLolPO2iZgI/8i4K0ba4mdpYLg9cdTOgeeYiw7HYH7M72dHw1yOX8DLK9+jpDB2/alO4taXaV271B5i/OWb5MVtIpfHexejI6DWtNK2Kj2fjzu7FsTtzeL//Bi8jCjg0eOKS9Pq+ykKDoHP4xRNgFPjqsgxGoghM/bC3Qt5hkvVQ2zZrtdvf3Tit+W9K41YmW0JSmI/cDCsLiH0FRvzN0tM7olF0LkvBOFw4xluztK7A9jMnsvazs91gQGwq5diDfFiXu4=
  file: $HOME/smart-home-configurator.tar.gz
  skip_cleanup: true
  on:
    branch: master
    repo: e154/smart-home-configurator

notifications:
  email:
    on_success: never
    on_failure: always