name: Build and Deploy

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

env:
  GITHUB_OAUTH_TOKEN: ${{ secrets.GITHUBTOKEN }}
  TRAVIS_BUILD_NUMBER: ${{ github.run_number }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

jobs:
  build:
    if: github.event.base_ref == 'refs/heads/master'
    name: Build_Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Checkout
        uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        env:
          RELEASE_VERSION: ${{ env.RELEASE_VERSION }}

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Prepary deps
        run: |
          echo -e "machine github.com\n  login ${{ secrets.GITHUBTOKEN }}" > ~/.netrc
          make get_deps

      - name: Build all
        id: build-all
        run: make all

      - name: Deploy docker image
        id: deploy-docker
        run: make deploy

      - uses: actions/upload-artifact@v2
        with:
          name: configurator
          path: /home/runner/smart-home-configurator.tar.gz
